export const authContent = {
  login: {
    title: "Iniciar sesión",
    registerText: "¿Aún no tienes cuenta?",
    registerLinkText: "Regístrate aquí",
    submitButtonLabel: "Ingresar",
    googleButtonLabel: "Continuar con Google",
    dividerText: "O continuar con",
    forgotPasswordText: "¿Olvidaste tu contraseña?",
    emailLabel: "Correo Electrónico",
    emailPlaceholder: "ejemplo@correo.com",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "Ingresa tu contraseña",
    welcomeSuccess: "Has iniciado sesión correctamente.",
    welcomeTitle: "¡Bienvenido de vuelta, {name}!"
  },
  register: {
    title: "Crear cuenta",
    loginText: "¿Ya tienes cuenta?",
    loginLinkText: "Inicia sesión aquí",
    backToShopText: "Volver a la tienda sin registrarme",
    submitButtonLabel: "Crear mi cuenta",
    googleButtonLabel: "Continuar con Google",
    dividerText: "O continuar con",
    termsText: "Acepto los",
    termsLink: "Términos y condiciones",
    privacyText: "y la",
    privacyLink: "Política de privacidad",
    termsErrorMsg: "Debes aceptar los términos para continuar",
    firstNameLabel: "Nombre",
    firstNamePlaceholder: "Juan",
    lastNameLabel: "Apellido",
    lastNamePlaceholder: "Pérez",
    emailLabel: "Correo electrónico",
    emailPlaceholder: "tu@correo.com",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "Mínimo 8 caracteres",
    welcomeSuccess: "Iniciando sesión automáticamente...",
    welcomeTitle: "Cuenta creada"
  },
  forgotPassword: {
    title: "Olvidé mi contraseña",
    description: "Ingresa el correo electrónico asociado a tu cuenta.",
    submitButtonLabel: "Enviar enlace de recuperación",
    backText: "Volver al inicio de sesión",
    emailLabel: "Correo Electrónico",
    emailPlaceholder: "ejemplo@correo.com",
    successMsg: "Hemos enviado un enlace de recuperación a tu correo electrónico.",
    alertSuccessTitle: "Correo enviado",
    alertSuccessDetail: "Revisa tu bandeja de entrada o spam."
  },
  resetPassword: {
    title: "Crear nueva contraseña",
    description: "Ingresa tu nueva contraseña a continuación.",
    submitButtonLabel: "Restablecer contraseña",
    backText: "Volver al inicio de sesión",
    mismatchErrorMsg: "Las contraseñas no coinciden",
    passwordLabel: "Nueva Contraseña",
    passwordPlaceholder: "Mínimo 8 caracteres",
    confirmPasswordLabel: "Confirmar Contraseña",
    confirmPasswordPlaceholder: "Repite tu contraseña",
    invalidToken: "El enlace de recuperación es inválido o ha expirado.",
    alertSuccessTitle: "Contraseña actualizada",
    alertSuccessDetail: "Tu contraseña ha sido restablecida con éxito. Ya puedes iniciar sesión."
  },
  oauthCallback: {
    loadingText: "Completando inicio de sesión...",
    welcomeTitle: "Bienvenido",
    welcomeSuccess: "Has iniciado sesión con Google.",
    errorTitle: "Error",
    errorProcess: "No se pudo procesar la sesión de Google.",
    errorNoToken: "No se recibió el token de autenticación."
  },
  validation: {
    required: "Este campo es requerido.",
    email: "Ingresa un correo electrónico válido.",
    minlength: "Mínimo {requiredLength} caracteres.",
    maxlength: "Máximo {requiredLength} caracteres.",
    min: "El valor mínimo es {min}.",
    max: "El valor máximo es {max}.",
    pattern: "Formato inválido.",
    invalidField: "Campo inválido."
  },
  interceptors: {
    noConnectionTitle: "Sin conexión",
    noConnectionDetail: "No se pudo conectar al servidor. Verifica tu conexión e intenta de nuevo.",
    accessDeniedTitle: "Acceso denegado",
    accessDeniedDetail: "No tienes permisos para realizar esta acción.",
    notFoundTitle: "No encontrado",
    notFoundDetail: "El recurso solicitado no existe.",
    serverErrorTitle: "Error del servidor",
    serverErrorDetail: "Ocurrió un error inesperado. Por favor intenta de nuevo."
  }
};
